name: C/C++ CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev 
    - name: configure
      run: chmod +x ./configure ; configure
    - name: make
      run: make
    - name: make test
      run: make test
